This will implement a basic percepton in Python using back propagation

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x*(1-x)

In [4]:
training_inputs=np.array([[0,0,1],
                        [1,1,1],
                        [1,0,1],
                        [0,1,1]])

In [5]:
training_outputs=np.array([[0,1,1,0]]).T

In [6]:
np.random.seed(1)

In [7]:
synaptic_weights=2*np.random.random((3,1))-1

In [8]:
print("Random starting synaptic weights: ")
print(synaptic_weights)

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [9]:
for iteration in range(50000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer,synaptic_weights))
    # Calculkate errors
    errors = training_outputs - outputs
    # Calculate the adjustment to the weights 
    adjustments = errors*sigmoid_derivative(outputs)
    # Adjust the weights
    synaptic_weights += np.dot(input_layer.T,adjustments)

In [10]:
print("Synaptic layer after training: ")
print(synaptic_weights)

Synaptic layer after training: 
[[11.30926129]
 [-0.20509237]
 [-5.45001623]]


In [11]:
print("After our Training: ")
print(outputs)

After our Training: 
[[0.0042779 ]
 [0.99650925]
 [0.99715469]
 [0.00348742]]


<img src="Capture.JPG">

In [12]:
np.dot(np.array([1,0,0]).T,synaptic_weights)

array([11.30926129])

In [13]:
sigmoid(np.dot(np.array([1,0,0]),synaptic_weights))

array([0.99998774])