Source: https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/solving-linear-systems/

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [2]:
A = np.array([[1,1,2],[-1,3,1],[0,5,2]])
print(A)

[[ 1  1  2]
 [-1  3  1]
 [ 0  5  2]]


In [3]:
E1 = np.array([[1,0,3],[0,1,0],[0,0,1]])
print(E1)

[[1 0 3]
 [0 1 0]
 [0 0 1]]


In [4]:
E1 @ A

array([[ 1, 16,  8],
       [-1,  3,  1],
       [ 0,  5,  2]])